name: Deploy to EC2

on:
    push:
        branches:
        - main

jobs:
    deploy:
        name: Push to EC2
        runs-on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Execute remote SSH commands using password
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: 100.54.142.163
                username: ubuntu
                key : ${{ secrets.AWS_GIT_ACTION_CI }}
                port: 20
                script: whoami

